CREATE VIEW [MDWT].[Salesperson] AS
SELECT [EmployeeKey]
      ,[BKEmployeeID]
      ,[NationalIDNumber]
      ,[EmployeeIDName]
      ,[EmployeeFullName]
      ,[EmployeeFirstName]
      ,[EmployeeLastName]
      ,[EmployeeMiddleName]
      ,[BirthDate]
      ,[MaritalStatus]
      ,[Gender]
      ,[IsSalaried]
      ,[IsCurrentEmployee]
      ,[IsSalesPerson]
      ,[JobTitle]
      ,[DepartmentID]
      ,[Department]
      ,[DepartmentGroup]
      ,[BKCurrentSalesTerritoryId]
      ,[CurrentSalesTerritory]
      ,[CurrentSalesTerritoryCountry]
      ,[CurrentSalesTerritoryGroup]
      ,[BKHistoricalSalesTerritoryId]
      ,[HistoricalSalesTerritory]
      ,[HistoricalSalesTerritoryCountry]
      ,[HistoricalSalesTerritoryGroup]
      ,[HireDate]
      ,[EmploymentEndDate]
      ,[LoginID]
      ,[EmployeeEmail]
      ,[EmployeePhone]
      ,[RowIsCurrent]
      ,[RowStartDate]
      ,[RowEndDate]
      ,[RowChangeReason]
  FROM [MDWT_2008R2].[dbo].[DimEmployee]
  --WHERE IsSalesPerson = 'y'
